---
- name: Create config directories
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/audiobookshelf/{{ item }}"
    state: directory
  loop:
    - config
    - metadata
    - audiobooks
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:{{ audiobookshelf_version }}
    state: quadlet
    quadlet_filename: audiobookshelf-container
    network: podman1
    ports:
      - 127.0.0.1:{{ audiobookshelf_port }}:80
    volumes:
      - "{{ podman_data_dir }}/audiobookshelf/config:/config:rw"
      - "{{ podman_data_dir }}/audiobookshelf/metadata:/metadata:rw"
      - "{{ podman_data_dir }}/audiobookshelf/audiobooks:/audiobooks:ro"
    env:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for audiobookshelf
    - Restart audiobookshelf
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/sites-enabled/audiobookshelf.Caddyfile
    group: 1000
    mode: "0644"
    owner: 1000
  notify:
    - Reload systemd for audiobookshelf
    - Restart audiobookshelf
- name: Copy borgmatic config
  become: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/audiobookshelf.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
