---
all:
  hosts:
    nuc:
    client_vps:
    workstation:
    office_pc:
    cluster0:
    cluster1:
    cluster2:

  children:
    linux_hosts:
      hosts:
        nuc:
        client_vps:
        workstation:
    servers:
      hosts:
        nuc:
        workstation:
    guests:
      hosts:
        client_vps:
    clients:
      hosts:
        client_vps:
        workstation:
    hypervisors:
      hosts:
        nuc:
        workstation:
    boxes:
      hosts:
        nuc:
        workstation:
    exit_nodes:
      hosts:
        nuc:
        workstation:
    interactive_boxes:
      hosts:
        workstation:
    container_hosts:
      hosts:
        nuc:
        workstation:
    labs:
      hosts:
        cluster0:
        cluster1:
        cluster2:
