---
all:
  children:
    servers:
      hosts:
        nuc:
          ansible_host: "{{ domain_name }}"
        recipe_vps:
          ansible_host: "{{ domain_name }}"
    clients:
      hosts:
        client:
          ansible_host: "{{ domain_name }}"
    hypervisors:
      hosts:
        nuc:
