---
all:
  hosts:
    nuc:
      ansible_host: "{{ domain_name }}"
    recipe_vps:
      ansible_host: "{{ domain_name }}"
    client_vps:
      ansible_host: "{{ domain_name }}"
    workstation:
      ansible_host: "{{ domain_name }}"

  children:
    servers:
      hosts:
        nuc:
        recipe_vps:
    guests:
      hosts:
        client_vps:
        recipe_vps:
    clients:
      hosts:
        client_vps:
        workstation:
    hypervisors:
      hosts:
        nuc:
    boxes:
      hosts:
        nuc:
        workstation:
    container_hosts:
      hosts:
        nuc:
        recipe_vps:
