---
- name: Base
  hosts: all
  roles:
    - system
    - editor
    - backups
    - artis3n.tailscale.machine
- name: Server base
  hosts: servers
  roles:
    - role: geerlingguy.repo-epel
      become: true
    - firewall
    - containers
    - notifications
    - reverse_proxy
- name: Client base
  hosts: clients
  roles:
    - journal
    - credentials
    - terminal
    - automation
    - version_control
    - file_manager
    - feed_client
- name: Nuc specific roles
  hosts: nuc
  roles:
    - hardware
    - disks
    - virtualization
    - admin_interface
    - photos
    - file_sync
    - feed_reader
    - bookmarks
    - ebooks
    - audiobooks
    - version_control_server
    - ai_client
- name: Recipe_vps specific roles
  hosts: recipe_vps
  roles:
    - recipes
    - ai_client
