---
- name: Base
  hosts: all
  roles:
    - role: geerlingguy.repo-epel
      become: true
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution != "Fedora"
    - system
    - editor
    - backups
    - containers
    - terminal
    - artis3n.tailscale.machine
- name: Server base
  hosts: servers
  roles:
    - firewall
    - notifications
    - reverse_proxy
- name: Client base
  hosts: clients
  roles:
    - credentials
    - automation
    - version_control
    - file_manager
    - feed_client
- name: Client base
  hosts: clients
  roles:
    - credentials
    - automation
    - version_control
    - file_manager
    - feed_client
- name: Physical box specific roles
  hosts: boxes
  roles:
    - hardware
    - disks
- name: Hypervisor specific roles
  hosts: hypervisors
  roles:
    - virtualization
    - admin_interface
- name: Nuc specific roles
  hosts: nuc
  roles:
    - photos
    - file_sync
    - feed_reader
    - bookmarks
    - ebooks
    - audiobooks
    - version_control_server
    - ai_client
- name: Recipe_vps specific roles
  hosts: recipe_vps
  roles:
    - recipes
    - ai_client
- name: Client_vps specific roles
  hosts: client_vps
  roles:
    - journal
