---
- name: Configure hypervisor
  hosts: nuc
  vars_files:
    - vars/nuc_vault.yml
  roles:
    - role: geerlingguy.repo-epel
      become: true
    - role: system
    - role: hardware
    - role: firewall
    - role: artis3n.tailscale.machine
    - role: disks
    - role: notifications
    - role: backups
    - role: virtualization
    - role: containers
    - role: reverse_proxy
    - role: admin_interface
    - role: photos
    - role: file_sync
    - role: feed_reader
    - role: bookmarks
    - role: ebooks
    - role: audiobooks
    - role: version_control_server
    - role: ai_client
#- name: Configure recipe_vps
#  hosts: recipe_vps
#  vars_files:
#    - vars/recipe_vps_vault.yml
#  roles:
#   - role: system
- name: Configure client
  hosts: client
  vars_files:
    - vars/client_vault.yml
  roles:
    - role: system
    - role: artis3n.tailscale.machine
    - role: backups
    - role: journal
    - role: credentials
    - role: terminal
    - role: automation
    - role: version_control
    - role: file_manager
    - role: feed_client
