---
- name: Configure system
  hosts: nuc
  vars_files:
    - vars/public.yml
    - vars/vault.yml
  roles:
    - role: geerlingguy.repo-epel
      become: true
    - role: system
    - role: hardware
    - role: firewall
    - role: artis3n.tailscale.device
    - role: disks
    - role: notifications
    - role: backups
    - role: virtualization
    - role: containers
    - role: reverse_proxy
    - role: admin_interface
    - role: photos
    - role: file_sync
    - role: feed_reader
