---
collections:
  - name: community.general
    version: "12.1.0"
  - name: artis3n.tailscale
    version: "1.1.0"
  - name: chocolatey.chocolatey
    version: "1.5.3"
  - name: containers.podman
    version: "1.18.1"
  - name: ansible.posix
    version: "2.1.0"
  - name: community.libvirt
    version: "2.0.0"
  - name: ansible.windows
    version: "3.3.0"
roles:
  - name: geerlingguy.repo-epel
    version: "3.1.1"
  - name: buluma.rpmfusion
    version: "24.3.31"
