---
collections:
  - name: community.general
    version: "10.7.0"
  - name: artis3n.tailscale
    version: "1.0.1"
roles:
  - name: geerlingguy.repo-epel
    version: "3.1.1"
  - name: buluma.rpmfusion
    version: "24.3.31"
  - name: geerlingguy.nfs
    version: "2.1.1"
  - name: robertdebock.autofs
    version: "2.1.10"
