---
collections:
  - name: community.general
    version: "10.7.0"
  - name: artis3n.tailscale
    version: "1.0.1"
  - name: chocolatey.chocolatey
    version: "1.5.3"
roles:
  - name: geerlingguy.repo-epel
    version: "3.1.1"
  - name: buluma.rpmfusion
    version: "24.3.31"
