---
- name: Set up laptop
  hosts: localhost
  vars_files:
    - group_vars/clients/vars.yml
    - group_vars/clients/vault.yml
  vars:
    group: staff
  tasks:
    - name: Install formulae
      ansible.builtin.import_tasks: common/tasks/install_brew_formulae.yml
      vars:
        brew_formulae:
          - ansible
          - ansible-lint
          - pass
          - borgbackup
          - lz4
          - fd
          - neovim
          - openssl@3
          - openssh
          - ripgrep
          - rsync
          - shellcheck
          - poppler
          - yt-dlp
          - ffmpeg
          - zsh-completion
          - fzf
          - zsh-autosuggestions
    - name: Install casks
      ansible.builtin.import_tasks: common/tasks/install_brew_casks.yml
      vars:
        brew_casks:
          - caffeine
          - discord
          - firefox
          - jagex
          - obsidian
          - runelite
          - signal
          - tailscale-app
          - vorta
          - logseq
          - iina
    - name: Install apps
      ansible.builtin.import_tasks: common/tasks/install_mas_apps.yml
      vars:
        mas_apps:
          - 360593530 # Notability
          - 375589283 # Parcel
          - 1289583905 # Pixelmator Pro
    - name: Uninstall apps
      ansible.builtin.import_tasks: common/tasks/uninstall_mas_apps.yml
      vars:
        mas_apps:
          - 682658836 # Garageband
          - 408981434 # iMovie
          - 409183694 # Keynote
          - 409203825 # Numbers
          - 409201541 # Pages
  roles:
    - version_control
    - terminal
    - pim_client
    - ide
    - file_sync_client
    - file_manager
    - feed_client
