---
- name: Set up laptop
  hosts: localhost
  vars_files:
    - group_vars/clients/vars.yml
    - group_vars/clients/vault.yml
  vars:
    group: staff
  tasks:
    - name: Install formulae
      ansible.builtin.import_tasks: common/tasks/install_brew_formulae.yml
      vars:
        brew_formulae:
          - fd
          - ripgrep
          - rsync
          - shellcheck
          - zsh-completion
          - fzf
          - zsh-autosuggestions
    - name: Install casks
      ansible.builtin.import_tasks: common/tasks/install_brew_casks.yml
      vars:
        brew_casks:
          - caffeine
          - discord
          - firefox
          - jagex
          - obsidian
          - runelite
          - signal
          - tailscale-app
          - vorta
          - iina
    - name: Install apps
      ansible.builtin.import_tasks: common/tasks/install_mas_apps.yml
      vars:
        mas_apps:
          - 360593530 # Notability
          - 375589283 # Parcel
          - 1289583905 # Pixelmator Pro
    - name: Uninstall apps
      ansible.builtin.import_tasks: common/tasks/uninstall_mas_apps.yml
      vars:
        mas_apps:
          - 682658836 # Garageband
          - 408981434 # iMovie
          - 409183694 # Keynote
          - 409203825 # Numbers
          - 409201541 # Pages
    - name: Adding pwfeedback
      become: true
      ansible.builtin.copy:
        content: |
          Defaults        pwfeedback
        dest: /etc/sudoers.d/02-pwfeedback
        group: wheel
        mode: "0440"
        owner: root
        validate: /usr/sbin/visudo -cf %s
    - name: Read com.apple.Dock autohide value
      become: false
      ansible.builtin.command: defaults read com.apple.Dock autohide
      register: autohide
      changed_when: false
    - name: Set dock to autohide
      become: false
      ansible.builtin.command: defaults write com.apple.dock autohide -bool TRUE
      when: autohide.stdout == "0"
      notify: Kill (and restart) the Dock
      changed_when: true
    - name: Read com.apple.dock wvous-tl-corner value
      become: false
      ansible.builtin.command: defaults read com.apple.dock wvous-tl-corner
      register: tlcorner
      changed_when: false
    - name: Set top left corner to Mission Control
      become: false
      ansible.builtin.command: defaults write com.apple.dock wvous-tl-corner -int 2
      when: tlcorner.stdout != "2"
      notify: Kill (and restart) Finder
      changed_when: true
  roles:
    - version_control
    - terminal
    - pim_client
    - ide
    - file_sync_client
    - file_manager
    - feed_client
    - email_client
    - editor
    - credentials
    - automation
    - backups
    - containers
  handlers:
    - name: Kill (and restart) the Dock
      changed_when: true
      ansible.builtin.command: killall Dock
    - name: Kill (and restart) Finder
      changed_when: true
      ansible.builtin.command: killall Finder
