---
# This is separate from my main hosts as of right now, it's not online all the time and non-standard.
# It is very incomplete
- name: Set up Macbook
  hosts: localhost
  tasks:
    - name: Install formulae
      ansible.builtin.import_tasks: common/tasks/install_brew_formulae.yml
      vars:
        brew_formulae:
          - ansible
          - ansible-lint
          - bitwarden-cli
          - borgbackup
          - lz4
          - fd
          - git
          - neovim
          - openssl@3
          - openssh
          - ripgrep
          - rsync
          - shellcheck
          - tmux
    - name: Install casks
      ansible.builtin.import_tasks: common/tasks/install_brew_casks.yml
      vars:
        brew_casks:
          - anki
          - balenaetcher
          - caffeine
          - discord
          - firefox@esr
          - font-noto-sans-cjk
          - iterm2
          - jagex
          - obsidian
          - pdk
          - runelite
          - rectangle
          - signal
          - steam
          - syncthing
          - syncthing-app
          - tailscale
          - tailscale-app
          - visual-studio-code
          - vorta
          - webex

