---
- name: Set up labs
  hosts: labs
  tasks:
    - name: Set the hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
  roles:
    - artis3n.tailscale.machine
