---
- name: Set up laptop
  hosts: localhost
  tasks:
    - name: Install formulae
      ansible.builtin.import_tasks: common/tasks/install_brew_formulae.yml
      vars:
        brew_formulae:
          - ansible
          - git
          - pass
    - name: Adding pwfeedback
      become: true
      ansible.builtin.copy:
        content: |
          Defaults        pwfeedback
        dest: /etc/sudoers.d/02-pwfeedback
        group: wheel
        mode: "0440"
        owner: root
        validate: /usr/sbin/visudo -cf %s
    - name: Read com.apple.Dock autohide value
      become: false
      ansible.builtin.command: defaults read com.apple.Dock autohide
      register: autohide
      changed_when: false
    - name: Set dock to autohide
      become: false
      ansible.builtin.command: defaults write com.apple.dock autohide -bool TRUE
      when: autohide.stdout == "0"
      notify: Kill (and restart) the Dock
      changed_when: true
    - name: Read com.apple.dock wvous-tl-corner value
      become: false
      ansible.builtin.command: defaults read com.apple.dock wvous-tl-corner
      register: tlcorner
      changed_when: false
    - name: Set top left corner to Mission Control
      become: false
      ansible.builtin.command: defaults write com.apple.dock wvous-tl-corner -int 2
      when: tlcorner.stdout != "2"
      notify: Kill (and restart) Finder
      changed_when: true
  handlers:
    - name: Kill (and restart) the Dock
      become: true
      changed_when: true
      ansible.builtin.command:
        cmd: killall Dock
    - name: Kill (and restart) Finder
      become: true
      changed_when: true
      ansible.builtin.command:
        cmd: killall Finder
