---
- name: Set up labs
  hosts: labs
  tasks:
    - name: Set the hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    - name: Add /usr/local/bin to PATH
      become: true
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: 'export PATH="$PATH:/usr/local/bin"'
        create: true
        owner: root
        group: root
        mode: "0644"
    - name: Install packages
      ansible.builtin.import_tasks: common/tasks/install_packages.yml
      vars:
        packages:
          - bash-completion
          - vim
  roles:
    - artis3n.tailscale.machine
