---
- name: Set up laptop
  hosts: localhost
  vars_files:
    - group_vars/clients/vars.yml
    - group_vars/clients/vault.yml
  vars:
    group: staff
    neomutt_theme: "https://raw.githubusercontent.com/marcothms/mutt-nord/refs/heads/master/nord.theme"
  tasks:
    - name: Install formulae
      ansible.builtin.import_tasks: common/tasks/install_brew_formulae.yml
      vars:
        brew_formulae:
          - fd
          - ripgrep
          - rsync
          - shellcheck
          - zsh-completion
          - fzf
          - zsh-autosuggestions
    - name: Install casks
      ansible.builtin.import_tasks: common/tasks/install_brew_casks.yml
      vars:
        brew_casks:
          - caffeine
          - discord
          - jagex
          - obsidian
          - runelite
          - signal
          - tailscale-app
          - vorta
          - iina
          - claude-code
    - name: Install apps
      ansible.builtin.import_tasks: common/tasks/install_mas_apps.yml
      vars:
        mas_apps:
          - 360593530 # Notability
          - 375589283 # Parcel
          - 1289583905 # Pixelmator Pro
          - 6443941139 # 2FAS Auth Browser Extension
          - 1352778147 # Bitwarden
          - 6746722790 # karakeeper
          - 1480933944 # Vimari
          - 6745342698 # uBlock Origin Lite
    - name: Uninstall apps
      ansible.builtin.import_tasks: common/tasks/uninstall_mas_apps.yml
      vars:
        mas_apps:
          - 682658836 # Garageband
          - 408981434 # iMovie
          - 409183694 # Keynote
          - 409203825 # Numbers
          - 409201541 # Pages
    - name: Adding pwfeedback
      become: true
      ansible.builtin.copy:
        content: |
          Defaults        pwfeedback
        dest: /etc/sudoers.d/02-pwfeedback
        group: wheel
        mode: "0440"
        owner: root
        validate: /usr/sbin/visudo -cf %s
    - name: Create iCloud symlink
      ansible.builtin.file:
        src: "~/Library/Mobile Documents/com~apple~CloudDocs"
        dest: "~/iCloud"
        state: link
    - name: Read com.apple.Dock autohide value
      become: false
      ansible.builtin.command: defaults read com.apple.Dock autohide
      register: autohide
      changed_when: false
    - name: Set dock to autohide
      become: false
      ansible.builtin.command: defaults write com.apple.dock autohide -bool TRUE
      when: autohide.stdout == "0"
      notify: Kill (and restart) the Dock
      changed_when: true
    - name: Read com.apple.dock wvous-tl-corner value
      become: false
      ansible.builtin.command: defaults read com.apple.dock wvous-tl-corner
      register: tlcorner
      changed_when: false
    - name: Set top left corner to Mission Control
      become: false
      ansible.builtin.command: defaults write com.apple.dock wvous-tl-corner -int 2
      when: tlcorner.stdout != "2"
      notify: Kill (and restart) Finder
      changed_when: true
    - name: Ensure omz custom functions directory exists
      ansible.builtin.file:
        path: "~/.oh-my-zsh/custom/functions"
        state: directory
        mode: "0755"
    - name: Download todoman zsh completion file
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/pimutils/todoman/refs/heads/main/contrib/completion/zsh/_todo
        dest: "~/.oh-my-zsh/custom/functions/_todo"
        mode: "0644"
        force: false
  roles:
    - version_control
    - terminal
    - pim_client
    - ide
    - file_sync_client
    - file_manager
    - feed_client
    - email_client
    - editor
    - credentials
    - automation
    - backups
    - containers
  handlers:
    - name: Kill (and restart) the Dock
      changed_when: true
      ansible.builtin.command: killall Dock
    - name: Kill (and restart) Finder
      changed_when: true
      ansible.builtin.command: killall Finder
