---
- name: Create config directories
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/calibre-web/{{ item }}"
    state: directory
  loop:
    - config
    - data
- name: Create config directories
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/calibre/Calibre Library"
    state: directory
- name: Allow Calibre-Web
  become: true
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "{{ calibre_web_port }}"
    comment: Calibre-Web
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: calibre-web
    image: docker.io/crocodilestick/calibre-web-automated:{{ calibre_web_version }}
    state: quadlet
    quadlet_filename: calibre-web-container
    network: host
    volumes:
      - "{{ podman_data_dir }}/calibre-web/config:/config:rw"
      - "{{ podman_data_dir }}/calibre-web/data:/cwa-book-ingest:rw"
      - "{{ podman_data_dir }}/calibre/Calibre Library:/calibre-library:rw"
    env:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for calibre
    - Restart calibre
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/sites-enabled/calibre.Caddyfile
    group: 1000
    mode: "0644"
    owner: 1000
  notify:
    - Reload systemd for calibre
    - Restart calibre
- name: Copy borgmatic config
  become: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/calibre.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
