---
- name: Copy cockpit config
  become: true
  ansible.builtin.template:
    dest: /etc/cockpit/cockpit.conf
    group: root
    mode: "0644"
    owner: root
    src: cockpit.conf.j2
  notify:
    - Reload systemd for cockpit
    - Restart cockpit
- name: Ensure socket systemd directory exists
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/cockpit.socket.d/
    state: directory
    mode: "0755"
- name: Copy cockpit listen config
  become: true
  ansible.builtin.template:
    dest: /etc/systemd/system/cockpit.socket.d/listen.conf
    group: root
    mode: "0644"
    owner: root
    src: listen.conf.j2
  notify:
    - Reload systemd for cockpit
    - Restart cockpit
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
