---
- name: Create config directories
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/{{ item }}"
    state: directory
  loop:
    - filebrowser/config
    - filebrowser/srv
    - filebrowser/database
- name: Create a Quadlet file
  become: true
  containers.podman.podman_container:
    name: filebrowser
    image: docker.io/filebrowser/filebrowser:{{ filebrowser_version }}
    state: quadlet
    quadlet_filename: filebrowser-container
    network: "{{ default_podman_interface }}"
    ports:
      - 127.0.0.1:{{ filebrowser_port }}:80
    volumes:
      - "{{ podman_data_dir }}/filebrowser/config:/config:rw"
      - "{{ podman_data_dir }}/filebrowser/database:/database:rw"
      - "{{ podman_data_dir }}/filebrowser/srv:/srv:rw"
    env:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for filebrowser
    - Restart filebrowser
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/sites-enabled/filebrowser.Caddyfile
    group: 1000
    mode: "0644"
    owner: 1000
  notify:
    - Reload systemd for filebrowser
    - Restart filebrowser
- name: Copy borgmatic config
  become: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/filebrowser.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
