---
- name: Create config directories
  become: true
  ansible.builtin.file:
    group: 1000
    mode: "0755"
    owner: 1000
    path: "{{ podman_data_dir }}/{{ item }}"
    state: directory
  loop:
    - radicale/config
    - radicale/data
- name: Create a Quadlet file for radicale
  become: true
  containers.podman.podman_container:
    name: radicale
    image: docker.io/tomsquest/docker-radicale:{{ radicale_version }}
    state: quadlet
    quadlet_filename: radicale-container
    user: 1000:1000
    env:
      TZ: America/New_York
    ports:
      - 127.0.0.1:{{ radicale_port }}:5232
    network: "{{ default_podman_interface }}"
    volumes:
      - "{{ podman_data_dir }}/radicale/config:/config:rw"
      - "{{ podman_data_dir }}/radicale/data:/data:rw"
    quadlet_options: "{{ default_quadlet_options }}"
  notify:
    - Reload systemd for radicale
    - Restart radicale
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Generate Caddyfile
  become: true
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/sites-enabled/radicale.Caddyfile
    group: 1000
    mode: "0644"
    owner: 1000
  notify:
    - Reload systemd for radicale
    - Restart radicale
- name: Copy borgmatic config
  become: true
  ansible.builtin.template:
    dest: /etc/borgmatic.d/radicale.yaml
    group: root
    mode: "0600"
    owner: root
    src: config.yaml.j2
