---
- name: Enable ufw
  become: true
  community.general.ufw:
    state: enabled
- name: Allow SSH
  become: true
  community.general.ufw:
    rule: allow
    proto: tcp
    port: 22
    comment: SSH
- name: Disable ufw logging (spams dmesg)
  become: true
  community.general.ufw:
    logging: "off"
