---
- name: Clean all machines
  hosts: linux_hosts
  tasks:
    - name: Autoremove unneeded packages installed as dependencies
      become: true
      ansible.builtin.dnf:
        autoremove: true
    - name: Prune podman images (System)
      become: true
      ansible.builtin.command: podman image prune -af
    - name: Prune podman volumes (System)
      become: true
      ansible.builtin.command: podman volume prune -f
    - name: Prune podman images (User)
      ansible.builtin.command: podman image prune -af
    - name: Prune podman volumes (User)
      ansible.builtin.command: podman volume prune -f
    - name: Prune unused flatpak packages
      when: "'interactive_boxes' in group_names"
      become: true
      ansible.builtin.command: flatpak remove --unused  -y
