---
# THIS IS A WORK IN PROGRESS
#
# First; install chocolatey & enable ssh
# Second: Make sure the pub key of the machine running ansible is on 'C:\ProgramData\ssh\administrators_authorized_keys' on the destination
#
# Manual packages:
#
# Intel XTU: Currently out of date on Chocolatey
# https://www.intel.com/content/www/us/en/download/17881/intel-extreme-tuning-utility-intel-xtu.html
#
# Jagex Launcher: No package
# https://www.jagex.com/launcher
#
# AmazonGames: Package is out of date/not working on Chocolatey
# https://www.amazon.com/gp/help/customer/display.html?nodeId=TQ1wROUN7BTxoTBbAk
#
# iCloud: Package is weird on Chocolatey.  Installs Bonjour and other unneeded things
# https://apps.microsoft.com/detail/9pktq5699m62?hl=en-US&gl=US
#
# TopNotify: No Chocolatey package
# https://github.com/SamsidParty/TopNotify/releases/download/3.1.0/Install.TopNotify.exe
- name: Install packages
  hosts: office_pc
  tasks:
    - name: Install packages
      ansible.builtin.import_tasks: ../common/tasks/install_choco_packages.yml
      vars:
        choco_packages:
          - vcredist140
          - dotnet-6.0-runtime
          - dotnet-8.0-runtime
          - discord
          - directx
          - syncthingtray
          - caffeine
          - magpie
          - 7zip
          - steam
          - tailscale
          - obsidian
          - epicgameslauncher
          - ea-app
          - goggalaxy
          - neovim
          - git
          - pdk
          - firefox
          - vscode
          - nvidia-app
          - logitech-options-plus
          - runelite
          - webex
          - ludusavi
          - stickies
          - libreoffice
          - mpvio
          - spotify
